name: CI (dev)
on:
  pull_request:
    branches:
      - dev
permissions:
  contents: read
  pull-requests: write

jobs:
  ci:
    name: Lint, format, typecheck, tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10.17.0

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Check runs lint, format:check, typecheck in one command
      - name: Check
        run: pnpm check

      - name: Enable auto-merge
        if: github.event_name == 'pull_request'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          merge-method: merge