name: CI (dev)
on:
  pull_request:
    branches:
      - dev
permissions:
  contents: read

jobs:
  ci:
    name: Lint, format, typecheck, tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      # Check runs lint, format:check, typecheck in one command
      - name: Check
        run: pnpm check