name: CI (main)
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
permissions:
  contents: read
  pull-requests: write

jobs:
  ci:
    name: Lint, Types, and Build check
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10.17.0

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Contentlayer types
        run: pnpm exec contentlayer build

      - name: Checks
        run: pnpm check

      - name: Install Doppler CLI
        run: |
          curl -sLf --retry 3 --retry-delay 2 https://cli.doppler.com/install.sh | sh

      - name: Build (with Doppler)
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
          NEXT_TELEMETRY_DISABLED: 1
        run: |
          pnpm run build

      - name: Enable auto-merge
        if: github.event_name == 'pull_request'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          merge-method: merge
