name: Promote dev to main

on:
  push:
    branches:
      - dev

permissions:
  contents: read
  pull-requests: write

jobs:
  ensure-pr:
    name: Ensure dev -> main PR exists
    runs-on: ubuntu-latest
    steps:
      - name: Create or update PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            const { data: existing } = await github.rest.pulls.list({
              owner,
              repo,
              state: 'open',
              head: `${owner}:dev`,
              base: 'main',
              per_page: 1,
            });

            if (existing.length > 0) {
              core.info(`Found existing PR #${existing[0].number}; no action needed.`);
              return;
            }

            const title = 'Promote dev to main';
            const body = [
              '## Summary',
              '',
              'Automatic promotion PR generated on push to `dev`.',
              '',
              'This PR keeps `main` up to date once `dev` changes pass checks.',
            ].join('\n');

            const { data: pr } = await github.rest.pulls.create({
              owner,
              repo,
              head: 'dev',
              base: 'main',
              title,
              body,
              maintainer_can_modify: true,
            });

            core.info(`Opened PR #${pr.number} to promote dev to main.`);
